# Permalinks
permalink:           pretty

# Setup
title:               End-To-End Human-Flying Robot Interaction
tagline:             Supplementary materials for "UAV, Come To Me; End-to-End, Multi-Scale Situated HRI with an Uninstrumented Human and a Distant UAV" paper (IROS 2016)
url:                 http://autonomylab.org
paginate:            1
baseurl:             /bebop_hri

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mani Monajjemi, Sepehr Mohaimenianpour, Richard Vaughan
  url:               http://autonomylab.org
  email:             TBA

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/AutonomyLab/bebop_hri

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
